# Generated by Django 4.2 on 2024-06-07 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
