# Generated by Django 4.2 on 2024-06-05 06:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_lesson_chapter_remove_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_chapter', to='course.chapter', verbose_name='chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_vid_pdf',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF')], default=1, max_length=10, verbose_name='lesson type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Default Title', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson/video/', verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='lesson/pdf/', verbose_name='content'),
        ),
    ]
