# Generated by Django 4.2 on 2024-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_chapter_options_chapter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='course', verbose_name='image'),
            preserve_default=False,
        ),
    ]
