# Generated by Django 4.2 on 2024-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
